apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job

spec:
  completions: 3 # Number of requested job to run (one-after-the-other, sequentially)
  parallelism: 3
  template:
    spec:
      containers:
      - name: math-add
        image: ubuntu
        command: ['expr', '3', '+', '2']
      restartPolicy: Never # <---
